---

log_level: trace
db_file_path: issuer.db
circuit_path: circuits/
key_dir: backend/keys

local_url: '0.0.0.0:8001'
public_url: https://6f2f-46-121-236-194.eu.ngrok.io

identity:
  secret_key: 30237d5b882221685f2926361ca7e81f1235d5faef02bcfbf99f459718bfd952
  merkle_tree_depth: 32
