log_level: TRACE   # TRACE/DEBUG/INFO
db_file_path: issuer.db
key_dir: keys
ipfs_url: ipfs.io
node_rpc_url:
contract_address: 0x46Fd04eEa588a3EA7e9F055dd691C688c4148ab3

identity:
  publishing_key:
  secret_key: 30237d5b882221685f2926361ca7e81f1235d5faef02bcfbf99f459718bfd780

local_url: 'localhost:8001'
public_url: https://b657-77-70-94-216.eu.ngrok.io
